name: checkpatch-test

on:
  push:
env:
  GITHUB_CONTEXT: ${{ toJson(github) }}
  run: echo "$GITHUB_CONTEXT"
  
jobs:
  Job1:
    name: target branch checking1
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref == 'main'   # check the target branch if it's master
    steps:
        - name: trigger
          run: echo "${{ github.base_ref }}"
               echo "${{github.event.pull_request.base.ref}}"
  Job2:
    name: target branch checking2
    runs-on: ubuntu-latest
    if: github.event.pull_request.base.ref != 'main' # check the target branch if it's master
    steps:
        - name: trigger
          run: echo Hello world from $GITHUB_HEAD_REF!
